# MSM8916 目标无 armsr 包源（armsr 是 ARM SystemReady 服务器目标，与高通410无关）
src/gz immortalwrt_base https://mirrors.pku.edu.cn/immortalwrt/releases/24.10-SNAPSHOT/packages/aarch64_generic/base
src/gz immortalwrt_luci https://mirrors.pku.edu.cn/immortalwrt/releases/24.10-SNAPSHOT/packages/aarch64_generic/luci
src/gz immortalwrt_packages https://mirrors.pku.edu.cn/immortalwrt/releases/24.10-SNAPSHOT/packages/aarch64_generic/packages
src/gz immortalwrt_routing https://mirrors.pku.edu.cn/immortalwrt/releases/24.10-SNAPSHOT/packages/aarch64_generic/routing
src/gz immortalwrt_telephony https://mirrors.pku.edu.cn/immortalwrt/releases/24.10-SNAPSHOT/packages/aarch64_generic/telephony